# Generated by Django 2.1.7 on 2019-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOIStorageRecord',
            fields=[
                ('AOIStorageRecordID', models.AutoField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(blank=True, max_length=50, null=True)),
                ('SerialNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('DateTime', models.DateTimeField()),
                ('StageName', models.CharField(max_length=50)),
                ('LineName', models.CharField(max_length=10)),
                ('FileType', models.CharField(max_length=1)),
                ('Path', models.CharField(max_length=512)),
                ('CreateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'AOIStorageRecord',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('StageID', models.AutoField(primary_key=True, serialize=False)),
                ('MfgType', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=2)),
                ('Description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Stage',
            },
        ),
    ]
