# Generated by Django 2.1.7 on 2019-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190620_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='MfgType',
            field=models.CharField(choices=[('PCB', 'PCB'), ('FA', 'FA')], default='PCB', max_length=3),
        ),
    ]
