# Generated by Django 2.1.7 on 2019-06-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190620_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('ConnectID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(choices=[('AOIServer1', 'AOIServer1'), ('AOIServer2', 'AOIServer2'), ('AOI3DXServer', 'AOI3DXServer')], max_length=20, unique=True)),
                ('Host', models.CharField(max_length=50)),
                ('Port', models.CharField(max_length=10)),
                ('User', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Timeout', models.CharField(blank=True, max_length=10, null=True)),
                ('AbsoluteDirPath', models.CharField(max_length=512)),
                ('Description', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'Connect',
            },
        ),
        migrations.AlterField(
            model_name='stage',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
