# Generated by Django 2.1.7 on 2019-06-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190621_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoistoragerecord',
            name='AOIStorageServer',
            field=models.CharField(choices=[('AOIServer1', 'AOIServer1'), ('AOIServer2', 'AOIServer2'), ('AOI3DXServer', 'AOI3DXServer')], default='AOIServer1', max_length=20),
        ),
    ]
