# Generated by Django 2.1.7 on 2019-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190625_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoistoragerecord',
            name='AOIStorageServer',
            field=models.CharField(choices=[('AOIServer', 'AOIServer'), ('AOI3DXServer', 'AOI3DXServer')], default='AOIServer', max_length=20),
        ),
    ]
