# Generated by Django 2.1.7 on 2019-06-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190625_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoistoragerecord',
            name='AOIStorageServer',
            field=models.CharField(choices=[('AOIServer', 'AOIServer'), ('AOI3DXServer', 'AOI3DXServer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='connect',
            name='Name',
            field=models.CharField(choices=[('AOIServer', 'AOIServer'), ('AOI3DXServer', 'AOI3DXServer')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Code',
            field=models.CharField(choices=[('T3', 'T3_SMT_SPI_TOP'), ('T9', 'T9_SMT_SPI_BOT'), ('TK', 'TK_SMT_AOI_TOP'), ('TL', 'TL_SMT_AOI_BOT'), ('T1', 'T1_DIP_AOI'), ('TY', 'TY_DIP_AOI2_IPC_RUNIN'), ('OA', 'OA_FINAL_DIP_AOI2'), ('T1', 'T1_FINAL_AOI'), ('IZ', 'IZ_FA_AOI'), ('FD', 'FD_AXI_OFFLINE_SAMPLINE'), ('FG', 'FG_AXI_ONLINE_DIP')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Name',
            field=models.CharField(choices=[('SMT_SPI_TOP', 'SMT_SPI_TOP'), ('SMT_SPI_BOT', 'SMT_SPI_BOT'), ('SMT_AOI_TOP', 'SMT_AOI_TOP'),('AXI_7600SIII','AXI_7600SIII'), ('SMT_AOI_BOT', 'SMT_AOI_BOT'), ('DIP_AOI', 'DIP_AOI'), ('DIP_AOI2_IPC_RUNIN', 'DIP_AOI2_IPC_RUNIN'), ('FINAL_DIP_AOI2', 'FINAL_DIP_AOI2'), ('FINAL_AOI', 'FINAL_AOI'), ('FA_AOI', 'FA_AOI'), ('AXI_OFFLINE_SAMPLINE', 'AXI_OFFLINE_SAMPLINE'), ('AXI_ONLINE_DIP', 'AXI_ONLINE_DIP')], max_length=50, unique=True),
        ),
    ]
