# Generated by Django 2.1.7 on 2019-06-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190625_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Description',
            field=models.CharField(choices=[('SMT_SPI(TOP)', 'SMT_SPI(TOP)'), ('SMT_SPI(BOT)', 'SMT_SPI(BOT)'), ('SMT_AOI(TOP)', 'SMT_AOI(TOP)'), ('SMT_AOI(BOT)', 'SMT_AOI(BOT)'),('AXI(7600SIII)','AXI(7600SIII)'), ('A Zone DIP_AOI', 'A Zone DIP_AOI'), ('DIP_AOI2&IPC Runin (Scan)', 'DIP_AOI2&IPC Runin (Scan)'), ('DIP_AOI2', 'DIP_AOI2'), ('B Zone Final_AOI', 'B Zone Final_AOI'), ('FA_AOI', 'FA_AOI'), ('X-Ray Offline Sampling (AXI)', 'X-Ray Offline Sampling (AXI)'), ('X-Ray Offline Sampling (AXI)', 'X-Ray Offline Sampling (AXI)')], max_length=50),
        ),
    ]
