# Generated by Django 2.1.7 on 2019-06-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190627_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Code',
            field=models.CharField(choices=[('T3', 'T3_SMT_SPI_TOP'), ('T9', 'T9_SMT_SPI_BOT'), ('TK', 'TK_SMT_AOI_TOP'), ('TL', 'TL_SMT_AOI_BOT'), ('T1', 'T1_DIP_AOI'), ('TY', 'TY_DIP_AOI2'), ('OA', 'OA_DIP_FINAL_AOI2'), ('T1', 'T1_DIP_FINAL_AOI'), ('IZ', 'IZ_FA_AOI'), ('FD/FG', 'AXI')], max_length=15, unique=True),
        ),
    ]
