# Generated by Django 2.1.7 on 2019-06-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20190627_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Code',
            field=models.CharField(choices=[('T3', 'T3_SMT_SPI_TOP'), ('T9', 'T9_SMT_SPI_BOT'), ('TK', 'TK_SMT_AOI_TOP'), ('TL', 'TL_SMT_AOI_BOT'), ('T1', 'T1_DIP_AOI'), ('TY', 'TY_DIP_AOI2'), ('OA', 'OA_DIP_FINAL_AOI2'), ('T1', 'T1_DIP_FINAL_AOI'), ('IZ', 'IZ_FA_AOI'), ('FD/FG', 'AXI')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Name',
            field=models.CharField(choices=[('SMT_SPI_TOP', 'SMT_SPI_TOP'), ('SMT_SPI_BOT', 'SMT_SPI_BOT'), ('SMT_AOI_TOP', 'SMT_AOI_TOP'), ('SMT_AOI_BOT', 'SMT_AOI_BOT'),('AXI_7600SIII','AXI_7600SIII'), ('DIP_AOI', 'DIP_AOI'), ('DIP_AOI2', 'DIP_AOI2'), ('DIP_FINAL_AOI2', 'DIP_FINAL_AOI2'), ('DIP_FINAL_AOI', 'DIP_FINAL_AOI'), ('FA_AOI', 'FA_AOI'), ('AXI_5DX', 'AXI_5DX'), ('AXI_7600SII', 'AXI_7600SII'), ('AXI_7600SIII', 'AXI_7600SIII')], max_length=50, unique=True),
        ),
    ]
