# Generated by Django 2.1.7 on 2019-08-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20190627_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('LineID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'Line',
            },
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('ModelNameID', models.AutoField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'ModelName',
            },
        ),
    ]
