# Generated by Django 2.1.7 on 2019-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_line_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='ModelName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
