# Generated by Django 2.1.7 on 2019-09-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20190820_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoistoragerecord',
            name='SerialNumber',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
