# Generated by Django 2.1.7 on 2019-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20191114_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('ComputerID', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(blank=True, max_length=50, unique=True)),
                ('LineName', models.CharField(blank=True, max_length=10)),
                ('StageName', models.CharField(blank=True, max_length=50)),
                ('LocalRootDirAbsPaths', models.CharField(max_length=512, null=True)),
                ('AOIStorageServer', models.CharField(max_length=20)),
                ('User', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Computer',
            },
        ),
    ]
