# Generated by Django 2.1.7 on 2020-03-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='OsType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
